### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by qcomer** [ildjarnisdead/Ncentral#5]
Hello,

Are you interested in any other contributors? I have added quite a bit to the module - active issues, service orgs, and some others.

I also re-organized the folder structure and applied scaffolding to the project. Broke the classes out into files and each function out into a file.

![image](https://github.com/ildjarnisdead/Ncentral/assets/7622826/6ced3fc3-edcf-4376-a641-b08e7089916a)

**Comment by ildjarnisdead** [comment]
Hi,

I have very little time to work on this. If you want to improve, feel free to create your own fork.

Joost
